services:
    nginx:
        container_name: nginx
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        restart: always
        ports:
            - "80:80"
        depends_on:
            - wordpress
        volumes:
            - wordpress_vol:/var/www/html
        networks:
            inception_net:
                ipv4_address: 10.0.0.1
    wordpress:
        container_name: wordpress
        env_file:
            - .env
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
            args:
                WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
                WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
                WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
                WORDPRESS_DB_PASS: ${WORDPRESS_DB_PASS}
        restart: always
        depends_on:
            - mariadb
        volumes:
            - wordpress_vol:/var/www/html
        networks:
            inception_net:
                ipv4_address: 10.0.0.2
    mariadb:
        container_name: mariadb
        env_file:
        - .env
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
            args:
                MARIADB_ROOT_PASS: ${MARIADB_ROOT_PASS}
                MARIADB_DB_NAME: ${MARIADB_DB_NAME}
                MARIADB_DB_USER: ${MARIADB_DB_USER}
                MARIADB_DB_PASS: ${MARIADB_DB_PASS}
        restart: always
        volumes:
            - db_vol:/var/lib/mysql
        networks:
            inception_net:
                ipv4_address: 10.0.0.3

volumes:
    db_vol: {}
    wordpress_vol: {}

networks:
    inception_net:
        name: inception_net
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.0.0.0/24
                  gateway: 10.0.0.254
