version: '3'

services:
    nginx:
        container_name: nginx
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        image: nginx:42
        restart: always
        ports:
            - "443:443"
        depends_on:
            - wordpress
        # volumes:
        #     - wordpress_vol:/path/to/wordpress
        networks:
            inception_net:
                ipv4_address: 172.42.0.1
        env_file:
            - .env

    mariadb:
        container_name: mariadb
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        image: mariadb:42
        restart: always
        # ports:
        #     - "9000:9000"
        # volumes:
        #     - db_vol:/path/to/mariadb/data
        networks:
            inception_net:
                ipv4_address: 172.42.0.2

    wordpress:
        container_name: wordpress
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        image: wordpress:42
        restart: always
        # ports:
            # - "3306:3306"
        depends_on:
            - mariadb
        # volumes:
        #     - wordpress_vol:/path/to/wordpress
        networks:
            inception_net:
                ipv4_address: 172.42.0.3

volumes:
    db_vol: {}
    wordpress_vol: {}

networks:
    inception_net:
        name: inception_net
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.42.0.0/24
                  gateway: 172.42.0.254
