services:
    nginx:
        container_name: nginx
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        restart: always
        ports:
            - "80:80"
        depends_on:
            - wordpress
        volumes:
            - wordpress_vol:/var/www/html
        networks:
            inception_net:
                ipv4_address: 10.0.0.1
    mariadb:
        container_name: mariadb
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - db_vol:/var/lib/mysql
        networks:
            inception_net:
                ipv4_address: 10.0.0.2
    wordpress:
        container_name: wordpress
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        restart: always
        environment:
            WORDPRESS_DB_HOST: db:3306
            WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
            WORDPRESS_DB_USER: ${MYSQL_USER}
            WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
        depends_on:
            - mariadb
        volumes:
            - wordpress_vol:/var/www/html
        networks:
            inception_net:
                ipv4_address: 10.0.0.3

volumes:
    db_vol: {}
    wordpress_vol: {}

networks:
    inception_net:
        name: inception_net
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.0.0.0/8
                  gateway: 10.255.255.254
